services:
  psycwall:
    image: psycwall:latest
    ports:
      - "80:8080"
    env_file:
      - .env.test
   
  redis:
   image: redis:7-alpine
   ports:
    - "6379:6379"
   volumes:
    - redis-data-psycwall:/data
   command: redis-server --appendonly yes

volumes:
  redis-data-psycwall:
